---
# tasks file for nginx
- name: update debian
  apt:
    update_cache=yes
- name: desinstall  apache2
  apt:
    name: apache2
    state: absent
- name: install  nginx
  apt:
    name: nginx
    state: present
- name: supprime default
  file:
    path: /etc/nginx/sites-available/default
    state: absent
- name: restart nginx
  systemd:
    name: nginx
    state: reloaded
- name: configuration des sites
  include: sites.yml
  with_items: "{{ locals }}"
- name: installation php
  include: php.yml
  notify: service php