---
- hosts: debian
  vars:
    user: dev
    locals:
      - local: local.dev
        php: yes
      - local: test.org
        php: no
  tasks:
  roles:
    - nginx
    - user
    - tools
    #- docker
    #- gitlab
    #- rancher