---
- hosts: all
  tasks:
    - name: update debian
      apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: update centos  
      yum: update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: install httpd centos
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: copie index.html
      template:
        src: /root/index.html
        dest: /var/www/html

    - name: demarrer apache2
      service:
        name: apache2
        state: started
      notify: restart apache2
      when: ansible_os_family == "Debian"

    - name: demarrer httpd
      service:
        name: httpd
        state: started
      notify: restart httpd
      when: ansible_os_family == "RedHat"

    - name: activer apache2
      service:
        name: apache2
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: activer httpd
      service:
        name: httpd
        enabled: yes
      when: ansible_os_family == "RedHat"

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: restart httpd
      service:
        name: httpd
        state: restarted
